services:
    postgres:
        image: postgres:17.5
        container_name: chat-app-postgres
        restart: always
        shm_size: 128mb
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=chat_app
        ports:
            - "5432:5432"
        volumes:
            - chat-app-postgres:/var/lib/postgresql/data
        networks:
            - chat-app
    mongo:
        image: mongo:latest
        container_name: chat-app-mongodb
        restart: always
        shm_size: 512mb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - chat-app-mongodb:/data/db
        networks:
            - chat-app

    adminer:
        image: adminer:5.3.0
        container_name: chat-app-adminer
        depends_on:
            - postgres
        restart: unless-stopped
        ports:
            - 8091:8080
        networks:
            - chat-app

    mongo-express:
        image: mongo-express
        container_name: chat-app-mongo-express
        depends_on:
            - mongo
        restart: unless-stopped
        ports:
            - 8092:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        networks:
            - chat-app

networks:
    chat-app:
        external: false
        name: chat-app

volumes:
    chat-app-postgres:
    chat-app-mongodb:
