apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: default
    labels:
        app: chatapp
        type: credentials
type: Opaque
stringData:
    MONGO_USER: mongo
    MONGO_PASSWORD: mongo
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    AUTH_SECRET: 52f887d9ae44b5691c5ea0a09563fe7e
    KEYCLOAK_CLIENT_SECRET: Pmntg88W18EqS0eNApJXgKI9Nge2g5KP
    MONGO_URI: mongodb://mongo:mongo@mongo:27017
    KEYCLOAK_ADMIN: keycloak
    POSTGRES_URI: postgresql://postgres:postgres@postgres:5432/chatapp?schema=public
