apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: default
    labels:
        app: chatapp
        type: credentials
type: Opaque
data:
    MONGO_USER: bW9uZ28K # mongo
    MONGO_PASSWORD: bW9uZ28K # mongo
    POSTGRES_USER: cG9zdGdyZXMK # postgres
    POSTGRES_PASSWORD: cG9zdGdyZXMK # postgres
    AUTH_SECRET: NTJmODg3ZDlhZTQ0YjU2OTFjNWVhMGEwOTU2M2ZlN2UK # 52f887d9ae44b5691c5ea0a09563fe7e
    KEYCLOAK_CLIENT_SECRET: UG1udGc4OFcxOEVxUzBlTkFwSlhnS0k5TmdlMmc1S1AK # Pmntg88W18EqS0eNApJXgKI9Nge2g5KP
    MONGO_URI: bW9uZ29kYjovL21vbmdvOm1vbmdvQG1vbmdvOjI3MDE3Cg== # mongodb://mongo:mongo@mongo:27017
    KEYCLOAK_ADMIN: a2V5Y2xvYWs= # keycloak
    POSTGRES_URI: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvY2hhdGFwcD9zY2hlbWE9cHVibGlj # postgresql://postgres:postgres@postgres:5432/chatapp?schema=public
