apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: default
    labels:
        app: chatapp
        type: credentials
type: Opaque
data:
    MONGO_USER: bW9uZ28= # mongo
    MONGO_PASSWORD: bW9uZ28= # mongo
    POSTGRES_USER: cG9zdGdyZXM= # postgres
    POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres
    AUTH_SECRET: NTJmODg3ZDlhZTQ0YjU2OTFjNWVhMGEwOTU2M2ZlN2U= # 52f887d9ae44b5691c5ea0a09563fe7e
    KEYCLOAK_CLIENT_SECRET: UG1udGc4OFcxOEVxUzBlTkFwSlhnS0k5TmdlMmc1S1A= # Pmntg88W18EqS0eNApJXgKI9Nge2g5KP
    MONGO_URI: bW9uZ29kYjovL21vbmdvOm1vbmdvQG1vbmdvOjI3MDE3 # mongodb://mongo:mongo@mongo:27017
    KEYCLOAK_ADMIN: a2V5Y2xvYWs= # keycloak
