apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: AUTH_SECRET
              value: 52f887d9ae44b5691c5ea0a09563fe7e
            - name: FRONTEND_URL
              value: http://frontend:5173
            - name: KEYCLOAK_CLIENT_ID
              value: frontend
            - name: KEYCLOAK_ISSUER
              value: http://keycloak:8082/realms/chatapp
            - name: MONGO_URI
              value: mongodb://mongo:mongo@mongo:27017
            - name: PORT
              value: "8083"
            - name: POSTGRES_URI
              value: postgresql://postgres:postgres@postgres:5432/chatapp?schema=public
          image: backend
          name: chatapp-backend
          ports:
            - containerPort: 8083
              protocol: TCP
      hostname: backend
      restartPolicy: Always
