apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.36.0 (ae2a39403)
    labels:
        io.kompose.service: backend
    name: backend
spec:
    replicas: 3
    selector:
        matchLabels:
            io.kompose.service: backend
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert --out k8s
                kompose.version: 1.36.0 (ae2a39403)
            labels:
                io.kompose.service: backend
        spec:
            containers:
                - env:
                      - name: AUTH_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: AUTH_SECRET
                      - name: FRONTEND_URL
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: FRONTEND_URL
                      - name: KEYCLOAK_CLIENT_ID
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: KEYCLOAK_CLIENT_ID
                      - name: KEYCLOAK_ISSUER
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: KEYCLOAK_ISSUER
                      - name: MONGO_URI
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: MONGO_URI
                      - name: PORT
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: PORT
                      - name: POSTGRES_URI
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: POSTGRES_URI
                  image: backend
                  imagePullPolicy: Never
                  name: chatapp-backend
                  ports:
                      - containerPort: 8083
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "256Mi"
            hostname: backend
            restartPolicy: Always
