apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: AUTH_SECRET
              value: 52f887d9ae44b5691c5ea0a09563fe7e
            - name: BACKEND_URL
              value: http://backend:8083
            - name: KEYCLOAK_CLIENT_ID
              value: frontend
            - name: KEYCLOAK_CLIENT_SECRET
              value: Pmntg88W18EqS0eNApJXgKI9Nge2g5KP
            - name: KEYCLOAK_ISSUER
              value: http://keycloak:8082/realms/chatapp
          image: frontend
          name: chatapp-frotend
          ports:
            - containerPort: 5173
              protocol: TCP
      restartPolicy: Always
