apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.36.0 (ae2a39403)
    labels:
        io.kompose.service: frontend
    name: frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            io.kompose.service: frontend
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert --out k8s
                kompose.version: 1.36.0 (ae2a39403)
            labels:
                io.kompose.service: frontend
        spec:
            containers:
                - env:
                      - name: AUTH_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: AUTH_SECRET
                      - name: BACKEND_URL
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: BACKEND_URL
                      - name: KEYCLOAK_CLIENT_ID
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: KEYCLOAK_CLIENT_ID
                      - name: KEYCLOAK_CLIENT_SECRE
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: KEYCLOAK_CLIENT_SECRET
                      - name: KEYCLOAK_ISSUER
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: KEYCLOAK_ISSUER
                  image: frontend
                  name: chatapp-frotend
                  ports:
                      - containerPort: 5173
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "256Mi"
            restartPolicy: Always
