apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: chatapp-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - http:
              paths:
                  - path: /api
                    pathType: Prefix
                    backend:
                        service:
                            name: backend
                            port:
                                number: 8083
                  - path: /auth
                    pathType: Prefix
                    backend:
                        service:
                            name: keycloak
                            port:
                                number: 8082
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 5173
