apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
    labels:
        io.kompose.service: mongo
    name: mongo
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: mongo
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
                kompose.version: 1.36.0 (ae2a39403)
            labels:
                io.kompose.service: mongo
        spec:
            containers:
                - env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            configMapKeyRef:
                                name: chatapp-config
                                key: MONGO_INITDB_ROOT_USERNAME
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: chatapp-secret
                                key: MONGO_INITDB_ROOT_PASSWORD
                  image: mongo:8.0.9
                  name: chatapp-mongodb
                  ports:
                      - containerPort: 27017
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /data/db
                        name: mongodb-data
            restartPolicy: Always
            volumes:
                - name: mongodb-data
                  persistentVolumeClaim:
                      claimName: mongodb-data
