apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.36.0 (ae2a39403)
    labels:
        io.kompose.service: mongo
    name: mongo
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: mongo
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert --out k8s
                kompose.version: 1.36.0 (ae2a39403)
            labels:
                io.kompose.service: mongo
        spec:
            containers:
                - env:
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: MONGO_PASSWORD
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: MONGO_USER
                  image: mongo:8.0.9
                  name: chatapp-mongodb
                  ports:
                      - containerPort: 27017
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "200m"
                          memory: "256Mi"
                      limits:
                          cpu: "1"
                          memory: "1Gi"
                  volumeMounts:
                      - mountPath: /data/db
                        name: mongodb-data
            restartPolicy: Always
            volumes:
                - name: mongodb-data
                  persistentVolumeClaim:
                      claimName: mongodb-data
